# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police_archive', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='officer',
            name='last_name',
        ),
        migrations.AddField(
            model_name='officer',
            name='name',
            field=models.CharField(default='Example Name', max_length=80),
            preserve_default=False,
        ),
    ]
