# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 13:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police_archive', '0003_auto_20160502_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officer',
            name='name',
        ),
        migrations.AddField(
            model_name='officer',
            name='first_name',
            field=models.CharField(default='fart', max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='officer',
            name='last_name',
            field=models.CharField(default='fart', max_length=80),
            preserve_default=False,
        ),
    ]
