# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police_archive', '0004_auto_20160503_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='case_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='finding',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='officer',
            name='badge',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='officer',
            name='department',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='officer',
            name='first_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='officer',
            name='last_name',
            field=models.CharField(blank=True, max_length=80),
        ),
    ]
