# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('police_archive', '0005_auto_20160503_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='officers',
        ),
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
