# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-04 15:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('police_archive', '0006_auto_20160504_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allegation', models.CharField(blank=True, max_length=50)),
                ('finding', models.CharField(blank=True, max_length=50)),
                ('action', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_number', models.CharField(blank=True, max_length=50)),
                ('office', models.CharField(choices=[('CRA', 'Civilian Review Authority'), ('IA', 'Internal Affairs'), ('OPCR', 'Office of Police Conduct Review')], max_length=10)),
                ('officers2', models.ManyToManyField(through='police_archive.Details', to='police_archive.Officer')),
            ],
        ),
        migrations.AddField(
            model_name='details',
            name='incident',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='police_archive.Incident'),
        ),
        migrations.AddField(
            model_name='details',
            name='officer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='police_archive.Officer'),
        ),
    ]
