# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police_archive', '0013_auto_20160922_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='model_pic',
            field=models.ImageField(default='noimage', upload_to='/officer_pictures/'),
        ),
    ]
