# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police_archive', '0016_auto_20161010_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='model_pic',
            field=models.ImageField(default='noimage', upload_to='{{static "/images/officer_images"}}'),
        ),
    ]
