# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-10 19:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police_archive', '0023_auto_20161010_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='model_pic',
            field=models.ImageField(default='noimage', upload_to='police_archive/officer_photos'),
        ),
    ]
