# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('police_archive', '0034_auto_20161216_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
